export const getMenuItemDetails = {
  GET_DETAILS_REQUEST: "GET_DETAILS_REQUEST",
  GET_DETAILS_SUCCESS: "GET_DETAILS_SUCCESS",
  GET_DETAILS_FAIL: "GET_DETAILS_FAIL",
};

export const createMenu = {
  CREATE_REQUEST: "CREATE_REQUEST",
  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_FAIL: "CREATE_FAIL",
  CREATE_RESET: "CREATE_RESET",
};

export const updateMenu = {
  M_UPDATE_REQUEST: "M_UPDATE_REQUEST",
  M_UPDATE_SUCCESS: "M_UPDATE_SUCCESS",
  M_UPDATE_FAIL: "M_UPDATE_FAIL",
  M_UPDATE_RESET: "M_UPDATE_RESET",
};

export const deleteMenu = {
  DELETE_REQUEST: "DELETE_REQUEST",
  DELETE_SUCCESS: "DELETE_SUCCESS",
  DELETE_FAIL: "DELETE_FAIL",
  DELETE_RESET: "DELETE_RESET",
};

export const setMenuAvailable = {
  SET_AVAILABLE_REQUEST: "SET_AVAILABLE_REQUEST",
  SET_AVAILABLE_SUCCESS: "SET_AVAILABLE_SUCCESS",
  SET_AVAILABLE_FAIL: "SET_AVAILABLE_FAIL",
};
