export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL";
export const PLACE_ORDER_RESET = "PLACE_ORDER_RESET";

export const DELIVER_ORDER_REQUEST = "DELIVER_ORDER_REQUEST";
export const DELIVER_ORDER_SUCCESS = "DELIVER_ORDER_SUCCESS";
export const DELIVER_ORDER_FAIL = "DELIVER_ORDER_FAIL";

export const FETCH_ORDER_REQUEST = "FETCH_ORDER_REQUEST";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = "FETCH_ORDER_FAIL";

export const PAY_ORDER_REQUEST = "PAY_ORDER_REQUEST";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_FAIL = "PAY_ORDER_FAIL";

export const GET_USER_ORDERS_REQUEST = "GET_USER_ORDERS_REQUEST";
export const GET_USER_ORDERS_SUCCESS = "GET_USER_ORDERS_SUCCESS";
export const GET_USER_ORDERS_FAIL = "GET_USER_ORDERS_FAIL";

export const GET_ALL_ORDERS_REQUEST = "GET_ALL_ORDERS_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";

export const GET_TODAYS_ORDERS_REQUEST = "GET_TODAYS_ORDERS_REQUEST";
export const GET_TODAYS_ORDERS_SUCCESS = "GET_TODAYS_ORDERS_SUCCESS";
export const GET_TODAYS_ORDERS_FAIL = "GET_TODAYS_ORDERS_FAIL";

export const GET_RESTO_ORDERS_REQUEST = "GET_RESTO_ORDERS_REQUEST";
export const GET_RESTO_ORDERS_SUCCESS = "GET_RESTO_ORDERS_SUCCESS";
export const GET_RESTO_ORDERS_FAIL = "GET_RESTO_ORDERS_FAIL";
