export const GET_RESTAURANTS_REQUEST = "GET_RESTAURANTS_REQUEST";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAIL = "GET_RESTAURANTS_FAIL";

export const GET_FEATURED_RESTAURANTS_REQUEST =
  "GET_FEATURED_RESTAURANTS_REQUEST";
export const GET_FEATURED_RESTAURANTS_SUCCESS =
  "GET_FEATURED_RESTAURANTS_SUCCESS";
export const GET_FEATURED_RESTAURANTS_FAIL = "GET_FEATURED_RESTAURANTS_FAIL";

export const GET_RESTAURANT_BY_ID_REQUEST = "GET_RESTAURANT_BY_ID_REQUEST";
export const GET_RESTAURANT_BY_ID_SUCCESS = "GET_RESTAURANT_BY_ID_SUCCESS";
export const GET_RESTAURANT_BY_ID_FAIL = "GET_RESTAURANT_BY_ID_FAIL";

//access for manager/ admin
export const ADD_RESTAURANT_REQUEST = "ADD_RESTAURANT_REQUEST";
export const ADD_RESTAURANT_SUCCESS = "ADD_RESTAURANT_SUCCESS";
export const ADD_RESTAURANT_FAIL = "ADD_RESTAURANT_FAIL";
export const ADD_RESTAURANT_RESET = "ADD_RESTAURANT_RESET";

export const EDIT_RESTAURANT_REQUEST = "EDIT_RESTAURANT_REQUEST";
export const EDIT_RESTAURANT_SUCCESS = "EDIT_RESTAURANT_SUCCESS";
export const EDIT_RESTAURANT_FAIL = "EDIT_RESTAURANT_FAIL";
export const EDIT_RESTAURANT_RESET = "EDIT_RESTAURANT_RESET";

export const DELETE_RESTAURANT_REQUEST = "DELETE_RESTAURANT_REQUEST";
export const DELETE_RESTAURANT_SUCCESS = "DELETE_RESTAURANT_SUCCESS";
export const DELETE_RESTAURANT_FAIL = "DELETE_RESTAURANT_FAIL";
export const DELETE_RESTAURANT_RESET = "DELETE_RESTAURANT_RESET";

export const getRestoByManager = {
  GET_RESTAURANT_BY_MANAGER_ID_REQUEST: "GET_RESTAURANT_BY_MANAGER_ID_REQUEST",
  GET_RESTAURANT_BY_MANAGER_ID_SUCCESS: "GET_RESTAURANT_BY_MANAGER_ID_SUCCESS",
  GET_RESTAURANT_BY_MANAGER_ID_FAIL: "GET_RESTAURANT_BY_MANAGER_ID_FAIL",
};
