export const MAKE_REVIEW_REQUEST = "MAKE_REVIEW_REQUEST";
export const MAKE_REVIEW_SUCCESS = "MAKE_REVIEW_SUCCESS";
export const MAKE_REVIEW_FAIL = "MAKE_REVIEW_FAIL";
export const MAKE_REVIEW_RESET = "MAKE_REVIEW_RESET";
